apiVersion: v1
kind: Pod
metadata:
  name: multic-pod
  labels:
    app: nginx-app
spec:
   containers:
   - name: nginx-c
     image: nginx
   - name: tomcat-c
     image: tomcat:9.0.115-jdk8-corretto-al2   
