apiVersion: v1
kind: Pod
metadata:
  name: taint-pod
spec:
   containers:
   - name: c1
     image: nginx
   tolerations:
   - key: "app"
     operator: "Equal"
     value: "web"
     effect: "NoSchedule"
